apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # Metal cloud config file (base64 encoded)
  kubeconfig: "abcdef123456" # Metal api kubeconfig
  namespace: "default" # Metal namespace where resources should be created
type: Opaque